name: Setup Flutter
description: setup shared Flutter environment for common use.

runs:
  using: "composite"

  steps:
    - name: Install and set Flutter version
      uses: subosito/flutter-action@v2
      with:
          flutter-version: "3.19.6"
    - name: Get Flutter packages
      run: |
        flutter pub get
      shell: bash


